#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=bootstrap/local-wsl/lib.sh
source "${SCRIPT_DIR}/lib.sh"

require_cmd curl
require_cmd docker
require_cmd python3
ensure_state_dir

wait_for_sonarqube() {
  local url="$1"
  local status
  for _ in $(seq 1 60); do
    status="$(curl -sS "${url%/}/api/system/status" 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin).get("status",""))' 2>/dev/null || true)"
    if [[ "${status}" == "UP" ]]; then
      log "SonarQube is UP at ${url}"
      return 0
    fi
    log "Waiting for SonarQube status=UP (current=${status:-unknown})..."
    sleep 5
  done
  return 1
}

sonar_auth_curl() {
  local user="$1"
  local password="$2"
  shift 2
  curl -fsS -u "${user}:${password}" "$@"
}

if docker ps -a --format '{{.Names}}' | grep -Fxq "${SONAR_CONTAINER_NAME}"; then
  log "SonarQube container already exists: ${SONAR_CONTAINER_NAME}"
  if ! docker ps --format '{{.Names}}' | grep -Fxq "${SONAR_CONTAINER_NAME}"; then
    log "Starting existing SonarQube container: ${SONAR_CONTAINER_NAME}"
    docker start "${SONAR_CONTAINER_NAME}" >/dev/null
  fi
else
  log "Creating SonarQube container: ${SONAR_CONTAINER_NAME}"
  docker run -d \
    --name "${SONAR_CONTAINER_NAME}" \
    --restart=always \
    -p 9000:9000 \
    -v secubank-sonarqube-data:/opt/sonarqube/data \
    -v secubank-sonarqube-extensions:/opt/sonarqube/extensions \
    sonarqube:community >/dev/null
fi

if ! wait_for_sonarqube "${SONAR_LOCAL_URL}"; then
  die "SonarQube did not become UP within 5 minutes. Check docker logs ${SONAR_CONTAINER_NAME}."
fi

if curl -fsS -u admin:admin "${SONAR_LOCAL_URL%/}/api/authentication/validate" | grep -q '"valid":true'; then
  log "Changing default SonarQube admin password."
  sonar_auth_curl admin admin -X POST "${SONAR_LOCAL_URL%/}/api/users/change_password" \
    -d "login=admin" \
    -d "previousPassword=admin" \
    -d "password=${SONAR_ADMIN_PASSWORD}" >/dev/null
else
  log "SonarQube default admin/admin is not active; assuming password was already changed."
fi

if sonar_auth_curl admin "${SONAR_ADMIN_PASSWORD}" "${SONAR_LOCAL_URL%/}/api/projects/search?projects=${SONAR_PROJECT_KEY}" | grep -q "\"key\":\"${SONAR_PROJECT_KEY}\""; then
  log "SonarQube project already exists: ${SONAR_PROJECT_KEY}"
else
  log "Creating SonarQube project: ${SONAR_PROJECT_KEY}"
  sonar_auth_curl admin "${SONAR_ADMIN_PASSWORD}" -X POST "${SONAR_LOCAL_URL%/}/api/projects/create" \
    -d "project=${SONAR_PROJECT_KEY}" \
    -d "name=${SONAR_PROJECT_KEY}" >/dev/null
fi

if [[ -f "${SONAR_TOKEN_FILE}" ]]; then
  log "Using cached SonarQube token file: ${SONAR_TOKEN_FILE}"
  exit 0
fi

token_response="${LOCAL_STATE_DIR}/sonarqube-token-response.json"
token_status="$(curl -sS -o "${token_response}" -w '%{http_code}' \
  -u "admin:${SONAR_ADMIN_PASSWORD}" \
  -X POST "${SONAR_LOCAL_URL%/}/api/user_tokens/generate" \
  -d "name=${SONAR_TOKEN_NAME}" || true)"

if [[ "${token_status}" != "200" ]]; then
  sed -n '1,200p' "${token_response}" >&2 || true
  die "Failed to generate SonarQube token; HTTP ${token_status}. If the token name already exists, revoke it in SonarQube UI or export SONAR_TOKEN manually."
fi

python3 - "${token_response}" "${SONAR_TOKEN_FILE}" <<'PY'
import json
import os
import shlex
import stat
import sys

with open(sys.argv[1], "r", encoding="utf-8") as fh:
    data = json.load(fh)
token = data.get("token")
if not token:
    raise SystemExit("SonarQube token response did not include token")

content = [
    "# Generated by bootstrap/local-wsl/05-install-sonarqube.sh",
    "# This file contains a SonarQube token. Do not commit it.",
    "SONAR_TOKEN=" + shlex.quote(token),
]
with open(sys.argv[2], "w", encoding="utf-8") as fh:
    fh.write("\n".join(content) + "\n")
os.chmod(sys.argv[2], stat.S_IRUSR | stat.S_IWUSR)
PY

log "Generated SonarQube token and wrote ${SONAR_TOKEN_FILE}"
