#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=bootstrap/local-wsl/lib.sh
source "${SCRIPT_DIR}/lib.sh"

require_cmd curl
require_cmd python3
ensure_state_dir

create_harbor_robot() {
  local response_file="${LOCAL_STATE_DIR}/harbor-robot-create-response.json"
  local payload_file="${LOCAL_STATE_DIR}/harbor-robot-create-payload.json"
  local status

  python3 - "${payload_file}" <<'PY'
import json
import os
import sys

project = os.environ["HARBOR_PROJECT"]
name = os.environ["HARBOR_ROBOT_NAME"]
payload = {
    "name": name,
    "description": "Robot account for secure-k8s-delivery-path Jenkins VulnBank MSA PoC",
    "disable": False,
    "duration": -1,
    "level": "project",
    "permissions": [
        {
            "kind": "project",
            "namespace": project,
            "access": [
                {"resource": "repository", "action": "pull"},
                {"resource": "repository", "action": "push"},
                {"resource": "artifact", "action": "read"},
                {"resource": "artifact", "action": "create"},
            ],
        }
    ],
}
with open(sys.argv[1], "w", encoding="utf-8") as fh:
    json.dump(payload, fh)
PY

  # Harbor v2.6+ removed /api/v2.0/projects/{name|id}/robots.
  # Use the unified /api/v2.0/robots endpoint; the payload's permissions[].namespace
  # already scopes this robot to the secubank project.
  status="$(curl -sS -o "${response_file}" -w '%{http_code}' \
    -u "${HARBOR_ADMIN_USER}:${HARBOR_ADMIN_PASSWORD}" \
    -H 'Content-Type: application/json' \
    -X POST "${HARBOR_URL%/}/api/v2.0/robots" \
    --data @"${payload_file}" || true)"

  case "${status}" in
    200|201)
      python3 - "${response_file}" "${HARBOR_ROBOT_ENV_FILE}" <<'PY'
import json
import os
import shlex
import stat
import sys

with open(sys.argv[1], "r", encoding="utf-8") as fh:
    data = json.load(fh)

username = data.get("name") or data.get("robot_name") or data.get("username")
secret = data.get("token") or data.get("secret") or data.get("password")
if not username or not secret:
    raise SystemExit("Harbor robot response did not include name/token")

content = [
    "# Generated by bootstrap/local-wsl/20-jenkins-credentials.sh",
    "# This file contains a Harbor robot secret. Do not commit it.",
    "HARBOR_ROBOT_USERNAME=" + shlex.quote(username),
    "HARBOR_ROBOT_PASSWORD=" + shlex.quote(secret),
]
with open(sys.argv[2], "w", encoding="utf-8") as fh:
    fh.write("\n".join(content) + "\n")
os.chmod(sys.argv[2], stat.S_IRUSR | stat.S_IWUSR)
print(username)
PY
      log "Created Harbor robot and wrote secret to ${HARBOR_ROBOT_ENV_FILE}"
      ;;
    409)
      die "Harbor robot ${HARBOR_ROBOT_NAME} already exists, but ${HARBOR_ROBOT_ENV_FILE} is missing. Harbor does not expose existing robot secrets. Export HARBOR_ROBOT_USERNAME/HARBOR_ROBOT_PASSWORD, or delete/recreate only this robot account manually."
      ;;
    *)
      sed -n '1,200p' "${response_file}" >&2 || true
      die "Harbor robot create failed; HTTP ${status}."
      ;;
  esac
}

if [[ -n "${HARBOR_ROBOT_USERNAME:-}" && -n "${HARBOR_ROBOT_PASSWORD:-}" ]]; then
  log "Using Harbor robot credentials from environment: ${HARBOR_ROBOT_USERNAME}"
elif [[ -f "${HARBOR_ROBOT_ENV_FILE}" ]]; then
  load_harbor_robot_env
  log "Using cached Harbor robot credentials from ${HARBOR_ROBOT_ENV_FILE}: ${HARBOR_ROBOT_USERNAME}"
else
  create_harbor_robot
  load_harbor_robot_env
fi

[[ -n "${HARBOR_ROBOT_USERNAME:-}" ]] || die "HARBOR_ROBOT_USERNAME is empty."
[[ -n "${HARBOR_ROBOT_PASSWORD:-}" ]] || die "HARBOR_ROBOT_PASSWORD is empty."
export HARBOR_ROBOT_USERNAME HARBOR_ROBOT_PASSWORD

credential_xml="${LOCAL_STATE_DIR}/jenkins-harbor-credential.xml"
python3 - "${credential_xml}" <<'PY'
import os
import sys
import xml.sax.saxutils as x

xml = f"""<com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
  <scope>GLOBAL</scope>
  <id>{x.escape(os.environ["JENKINS_CREDENTIAL_ID"])}</id>
  <description>Harbor robot account for VulnBank MSA local WSL PoC</description>
  <username>{x.escape(os.environ["HARBOR_ROBOT_USERNAME"])}</username>
  <password>{x.escape(os.environ["HARBOR_ROBOT_PASSWORD"])}</password>
</com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
"""
with open(sys.argv[1], "w", encoding="utf-8") as fh:
    fh.write(xml)
PY

crumb_args=()
while IFS= read -r item; do
  crumb_args+=("${item}")
done < <(jenkins_crumb_header_args)

credential_path="${JENKINS_URL%/}/credentials/store/system/domain/_/credential/$(urlencode "${JENKINS_CREDENTIAL_ID}")"
if jenkins_curl GET "${credential_path}/api/json" >/dev/null 2>&1; then
  jenkins_curl POST "${credential_path}/config.xml" "${crumb_args[@]}" \
    -H 'Content-Type: application/xml' \
    --data-binary @"${credential_xml}" >/dev/null
  log "Updated Jenkins credential: ${JENKINS_CREDENTIAL_ID}"
else
  jenkins_curl POST "${JENKINS_URL%/}/credentials/store/system/domain/_/createCredentials" "${crumb_args[@]}" \
    -H 'Content-Type: application/xml' \
    --data-binary @"${credential_xml}" >/dev/null
  log "Created Jenkins credential: ${JENKINS_CREDENTIAL_ID}"
fi

load_sonarqube_token_env
if [[ -n "${SONAR_TOKEN:-}" ]]; then
  export SONAR_TOKEN
  sonar_credential_xml="${LOCAL_STATE_DIR}/jenkins-sonarqube-token.xml"
  python3 - "${sonar_credential_xml}" <<'PY'
import os
import sys
import xml.sax.saxutils as x

xml = f"""<org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl>
  <scope>GLOBAL</scope>
  <id>{x.escape(os.environ["SONAR_TOKEN_CREDENTIAL_ID"])}</id>
  <description>SonarQube token for VulnBank MSA local WSL PoC</description>
  <secret>{x.escape(os.environ["SONAR_TOKEN"])}</secret>
</org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl>
"""
with open(sys.argv[1], "w", encoding="utf-8") as fh:
    fh.write(xml)
PY

  sonar_credential_path="${JENKINS_URL%/}/credentials/store/system/domain/_/credential/$(urlencode "${SONAR_TOKEN_CREDENTIAL_ID}")"
  if jenkins_curl GET "${sonar_credential_path}/api/json" >/dev/null 2>&1; then
    jenkins_curl POST "${sonar_credential_path}/config.xml" "${crumb_args[@]}" \
      -H 'Content-Type: application/xml' \
      --data-binary @"${sonar_credential_xml}" >/dev/null
    log "Updated Jenkins credential: ${SONAR_TOKEN_CREDENTIAL_ID}"
  else
    jenkins_curl POST "${JENKINS_URL%/}/credentials/store/system/domain/_/createCredentials" "${crumb_args[@]}" \
      -H 'Content-Type: application/xml' \
      --data-binary @"${sonar_credential_xml}" >/dev/null
    log "Created Jenkins credential: ${SONAR_TOKEN_CREDENTIAL_ID}"
  fi
else
  warn "SONAR_TOKEN was not found. Run bootstrap/local-wsl/05-install-sonarqube.sh or export SONAR_TOKEN before registering Jenkins SonarQube credentials."
fi

register_secret_text_credential() {
  local credential_id="$1"
  local description="$2"
  local secret_value="$3"
  local xml_file="${LOCAL_STATE_DIR}/jenkins-${credential_id}.xml"
  local credential_path

  export REGISTER_CREDENTIAL_ID="${credential_id}"
  export REGISTER_CREDENTIAL_DESCRIPTION="${description}"
  export REGISTER_CREDENTIAL_SECRET="${secret_value}"

  python3 - "${xml_file}" <<'PY'
import os
import sys
import xml.sax.saxutils as x

xml = f"""<org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl>
  <scope>GLOBAL</scope>
  <id>{x.escape(os.environ["REGISTER_CREDENTIAL_ID"])}</id>
  <description>{x.escape(os.environ["REGISTER_CREDENTIAL_DESCRIPTION"])}</description>
  <secret>{x.escape(os.environ["REGISTER_CREDENTIAL_SECRET"])}</secret>
</org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl>
"""
with open(sys.argv[1], "w", encoding="utf-8") as fh:
    fh.write(xml)
PY

  credential_path="${JENKINS_URL%/}/credentials/store/system/domain/_/credential/$(urlencode "${credential_id}")"
  if jenkins_curl GET "${credential_path}/api/json" >/dev/null 2>&1; then
    jenkins_curl POST "${credential_path}/config.xml" "${crumb_args[@]}" \
      -H 'Content-Type: application/xml' \
      --data-binary @"${xml_file}" >/dev/null
    log "Updated Jenkins credential: ${credential_id}"
  else
    jenkins_curl POST "${JENKINS_URL%/}/credentials/store/system/domain/_/createCredentials" "${crumb_args[@]}" \
      -H 'Content-Type: application/xml' \
      --data-binary @"${xml_file}" >/dev/null
    log "Created Jenkins credential: ${credential_id}"
  fi

  unset REGISTER_CREDENTIAL_ID REGISTER_CREDENTIAL_DESCRIPTION REGISTER_CREDENTIAL_SECRET
}

load_github_pat_env
if [[ -n "${GITHUB_PAT:-}" && -n "${GITHUB_USER:-}" ]]; then
  register_secret_text_credential "${GITHUB_PAT_CREDENTIAL_ID}" "GitHub PAT for pushing gitops-manifest-repo from Jenkins" "${GITHUB_PAT}"
  register_secret_text_credential "${GITHUB_USER_CREDENTIAL_ID}" "GitHub username for pushing gitops-manifest-repo from Jenkins" "${GITHUB_USER}"
else
  warn "GITHUB_PAT or GITHUB_USER was not found. Create ${GITHUB_PAT_FILE} or export both variables before registering GitHub GitOps credentials."
fi

log "Jenkins credentials are registered. The trigger script passes Harbor and SonarQube values as build parameters; GitHub PAT credentials are consumed by Jenkinsfile.msa withCredentials."
